# Generated by Django 5.0.6 on 2024-06-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.FileField(blank=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='pictureOutput',
            field=models.FileField(blank=True, upload_to='pictureSalida'),
        ),
    ]
